"""add activity_name, duration, activity_image, is_done, score to activity

Revision ID: 4c3ca9ffe963
Revises: 682fb8dd509b
Create Date: 2025-06-25 19:59:15.747624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3ca9ffe963'
down_revision = '682fb8dd509b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activity_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('is_done')
        batch_op.drop_column('activity_image')
        batch_op.drop_column('duration')
        batch_op.drop_column('activity_name')

    # ### end Alembic commands ###
