"""add extra fields to user: first_name, last_name, phone, country_code, doctor_specialty, child_birthdate, child_education_level

Revision ID: 00f14de5b57c
Revises: 
Create Date: 2025-06-24 14:12:13.927230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f14de5b57c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('Field6')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_education_level', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('child_education_level')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Field6', sa.INTEGER(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
