"""add child_problem field to user

Revision ID: 831a32a4c69b
Revises: 00f14de5b57c
Create Date: 2025-06-24 14:32:51.047113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831a32a4c69b'
down_revision = '00f14de5b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_problem', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('child_problem')

    # ### end Alembic commands ###
